### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by karthickvkumar** [zubricky/react-native-android-keyboard-adjust#3]
Hi @zubricky, Thanks for this awesome library. It would be more helpful if you add some working example or GIF to show the result

Thanks in Advance

**Comment by zubricky** [comment]
Hey @karthickvkumar, added some examples here: https://github.com/zubricky/react-native-android-keyboard-adjust/blob/master/Examples/KeyboardAdjustExample.android.js

Also added some screenshots showing adjust nothing vs adjust resize to the readme.

If you or anyone else wants to add some examples for other methods, feel free! Hopefully what's there now covers the basic use cases.
