### ISSUE TITLE
Packages aren't declared in MainActivity anymore

### ISSUE THREAD

**Issue by jr-k** [zubricky/react-native-android-keyboard-adjust#5]
Hi,

As the title say, package are loaded in MainApplication but your package needs an Activity reference. Is there a workaround for this issue ?

Thanks

**Comment by jreziga** [comment]
see https://github.com/facebook/react-native/releases/tag/v0.29.0


> Plugins which pass activity reference in the constructor need to be updated to extend ReactContextBaseJavaModule use getCurrentActivity to get the activity reference. This change is backward compatible.
Apps need to be migrated to use the latest template

**Comment by zubricky** [comment]
Branch merged into master. Thanks.
